apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wired-brain-coffee
  description: poc on sonarqube ananlysis dashboash through backstage.
  annotations:
    sonarqube.org/project-key: sqp_acf083c4bdef48f3ba523bc69099ba2897886368
spec:
  type: library
  owner: karsingh15
  lifecycle: experimental
